---
name: "CI"

"on":
  ## Events: Pushes on Main
  push:
    branches:
      - main
    paths:
      - docs/**/*.*
      - example/**/*.*
      - graalvm/**/*.*
      - internal/**/*.*
      - tools/**/*.*

jobs:
  build:
    name: "Build (${{ matrix.label }})"
    uses: ./.github/workflows/module.build.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            label: Ubuntu - Standard
            bzlmod: true
            labs: false
          - runner: ubuntu-latest
            label: Ubuntu - Bzlmod
            bzlmod: true
            labs: false
          - runner: windows-latest
            label: Windows
            bzlmod: false
            labs: true
          - runner: macos-latest
            label: macOS
            bzlmod: false
            labs: false

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}
      tests: true
