---
name: "PR"

"on":
  ## Run on PR filings
  pull_request:
    branches:
      - main
    paths:
      - docs/**/*.*
      - example/**/*.*
      - graalvm/**/*.*
      - internal/**/*.*
      - tools/**/*.*

  ## Run on PR queue check requests
  merge_group: {}

jobs:
  dependency-review:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - name: "Checkout Repository"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@7d90b4f05fea31dde1c4a1fb3fa787e197ea93ab # v3.0.7
        with:
          config-file: "./.github/dependency-review-config.yml"

  test:
    name: "Test (${{ matrix.label }})"
    uses: ./.github/workflows/module.build.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        bzlmod: [false]
        bazelversion: ["7.0.0-pre.20230724.1", "6.3.2", "5.4.0"]
        include:
          - runner: ubuntu-latest
            label: Ubuntu - Bazel 7
            labs: false
            bazelversion: 7.0.0-pre.20230724.1
          - runner: ubuntu-latest
            label: Ubuntu - Bzlmod 7
            bzlmod: true
            labs: true
            bazelversion: 7.0.0-pre.20230724.1
          - runner: windows-latest
            label: Windows - Bazel 7
            bzlmod: false
            labs: true
            bazelversion: 7.0.0-pre.20230724.1
          - runner: macos-latest
            label: macOS - Bazel 7
            bzlmod: false
            labs: false
            bazelversion: 7.0.0-pre.20230724.1
          - runner: ubuntu-latest
            label: Ubuntu - Bazel 6
            labs: false
            bazelversion: 6.3.2
          - runner: ubuntu-latest
            label: Ubuntu - Bzlmod 6
            bzlmod: true
            labs: true
            bazelversion: 6.3.2
          - runner: windows-latest
            label: Windows - Bazel 6
            bzlmod: false
            labs: true
            bazelversion: 6.3.2
          - runner: macos-latest
            label: macOS - Bazel 6
            bzlmod: false
            labs: false
            bazelversion: 6.3.2
          - runner: ubuntu-latest
            label: Ubuntu - Bazel 5
            labs: true
            bazelversion: 5.4.0
          - runner: windows-latest
            label: Windows - Bazel 5
            bzlmod: false
            labs: true
            bazelversion: 5.4.0
          - runner: macos-latest
            label: macOS - Bazel 5
            bzlmod: false
            labs: true
            bazelversion: 5.4.0

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}
      bazel_version: ${{ matrix.bazelversion }}
