---
name: "PR"

"on":
  pull_request:
    branches:
      - main

jobs:
  dependency-review:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: "Checkout Repository"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@7d90b4f05fea31dde1c4a1fb3fa787e197ea93ab # v3.0.7
        with:
          config-file: "./.github/dependency-review-config.yml"

  test:
    name: "Test (${{ matrix.label }})"
    uses: ./.github/workflows/module.test.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        bzlmod: [false]
        include:
          - runner: ubuntu-latest
            label: Ubuntu - Standard
            labs: false
          - runner: ubuntu-latest
            label: Ubuntu - Bzlmod
            bzlmod: true
            labs: true
          - runner: windows-latest
            label: Windows
            bzlmod: false
            labs: true
          - runner: macos-latest
            label: macOS
            bzlmod: false
            labs: false

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}
