---
name: "PR"

"on":
  ## Run on PR filings
  pull_request:
    branches:
      - main
    paths:
      - docs/**/*.*
      - example/**/*.*
      - graalvm/**/*.*
      - internal/**/*.*
      - tools/**/*.*

  ## Run on PR queue check requests
  merge_group: {}

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-graph:
    name: "Dependency Graph"
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Report: Dependency Graph"
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3 # v3.0.2

  dependency-review:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - name: "Checkout Repository"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@f6fff72a3217f580d5afd49a46826795305b63c7 # v3.0.8
        with:
          config-file: "./.github/dependency-review-config.yml"

  test:
    name: "Test"
    uses: ./.github/workflows/module.build.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        bzlmod: [false]
        bazelversion: ["7.0.0-pre.20230724.1"]
        bazel_config: ["bazel7"]
        main: [false]
        include:
          # Bazel 7
          - runner: ubuntu-latest
            label: Ubuntu / Bazel 7
            labs: false
            main: false
            bazelversion: 7.0.0-pre.20230724.1
            bazel_config: bazel7
          - runner: ubuntu-latest
            label: Ubuntu / Bzlmod 7
            bzlmod: true
            labs: false
            main: true
            bazelversion: 7.0.0-pre.20230724.1
            bazel_config: bazel7
          - runner: macos-latest
            label: macOS / Bazel 7
            bzlmod: true
            labs: false
            main: true
            bazelversion: 7.0.0-pre.20230724.1
            bazel_config: bazel7
          #          - runner: windows-latest
          #            label: Windows / Bazel 7
          #            bzlmod: false
          #            labs: true
          #            bazelversion: 7.0.0-pre.20230724.1
          #            bazel_config: bazel7

          # Bazel 6
          - runner: ubuntu-latest
            label: Ubuntu / Bazel 6
            labs: false
            bazelversion: 6.3.2
            bzlmod: false
            main: false
            bazel_config: bazel6
          - runner: macos-latest
            label: macOS / Bazel 6
            bzlmod: false
            labs: false
            main: false
            bazelversion: 6.3.2
            bazel_config: bazel6

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}
      bazel_version: ${{ matrix.bazelversion }}
      bazel_config: ${{ matrix.bazel_config }}
      main: ${{ matrix.main }}
