name: "CI"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/module.build.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            label: Ubuntu
            bzlmod: true
            labs: false
          - runner: windows-latest
            label: Windows
            bzlmod: false
            labs: true
          - runner: macos-latest
            label: macOS
            bzlmod: false
            labs: false

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}

  test:
    name: "Test"
    needs: ["build"]
    uses: ./.github/workflows/module.test.yml
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            label: Ubuntu
            labs: false
          - runner: ubuntu-latest
            label: Ubuntu - Bzlmod
            bzlmod: true
            labs: true
          - runner: windows-latest
            label: Windows
            bzlmod: false
            labs: true
          - runner: macos-latest
            label: macOS
            bzlmod: false
            labs: false

    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      label: ${{ matrix.label }}
      bzlmod: ${{ matrix.bzlmod }}
      labs: ${{ matrix.labs }}
