---
name: Release

"on":
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    name: "Release: BCR"
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v2
    with:
      release_files: rules_graalvm-*.zip
