---
name: Release

"on":
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    name: "Release: BCR"
    uses: elide-dev/bazel-contrib/.github/workflows/release_ruleset.yaml@master
    with:
      release_files: rules_graalvm-*.zip
      prerelease: false
